### ISSUE TITLE
Memory keep increasing when to ping many IPs.

### ISSUE THREAD

**Issue by Alexiusy** [chrishulbert/SimplePingHelper#5]
I have a problem on my Mac app. I want to ping 30 IPs every 30 seconds. And when I do this, I found my app's memory keep increasing. And when ping stops, the memory won't reduce. Then I start a testing project and get the same result. But if there is a few IPs and not so high frequency, all is work fine.

Am I use it in the wrong way?

**Comment by chrishulbert** [comment]
Hi,
Sounds like you have a memory leak. You should use Instruments to find
where it is. It may be in my library and it may also be in your code.
Good luck

**Comment by Alexiusy** [comment]
@chrishulbert Thank you for your reply. I have used Instruments and still do not know where the problem is. So I find a temporary solution.

THANKS.
